apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  labels:
    App: fastapi
spec:
  type: {{ .Values.service.type }}
  selector:
    App: fastapi
  ports:
    - name: http          # <---- IMPORTANT: port name for ServiceMonitor
      port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP

