version: "3.9"

services:
  api:
    build: .
    container_name: myapi
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_USER: manoj
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: devopsapp
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"

  db:
    image: postgres:14
    container_name: mydb
    environment:
      POSTGRES_USER: manoj
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: devopsapp
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

